// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tank_manager.proto

package com.myking520.github.protocolbuf;

public final class NetTankManager {
  private NetTankManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string pid = 1;
    boolean hasPid();
    String getPid();
  }
  public static final class Login extends
      com.google.protobuf.GeneratedMessage
      implements LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(Builder builder) {
      super(builder);
    }
    private Login(boolean noInit) {}
    
    private static final Login defaultInstance;
    public static Login getDefaultInstance() {
      return defaultInstance;
    }
    
    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_Login_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_Login_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private java.lang.Object pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPid() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      pid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.myking520.github.protocolbuf.NetTankManager.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.myking520.github.protocolbuf.NetTankManager.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_Login_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_Login_fieldAccessorTable;
      }
      
      // Construct using com.ele.net.server.proto.NetTankManager.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.myking520.github.protocolbuf.NetTankManager.Login.getDescriptor();
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.Login getDefaultInstanceForType() {
        return com.myking520.github.protocolbuf.NetTankManager.Login.getDefaultInstance();
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.Login build() {
        com.myking520.github.protocolbuf.NetTankManager.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.myking520.github.protocolbuf.NetTankManager.Login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.myking520.github.protocolbuf.NetTankManager.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.Login buildPartial() {
        com.myking520.github.protocolbuf.NetTankManager.Login result = new com.myking520.github.protocolbuf.NetTankManager.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.myking520.github.protocolbuf.NetTankManager.Login) {
          return mergeFrom((com.myking520.github.protocolbuf.NetTankManager.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.myking520.github.protocolbuf.NetTankManager.Login other) {
        if (other == com.myking520.github.protocolbuf.NetTankManager.Login.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string pid = 1;
      private java.lang.Object pid_ = "";
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPid() {
        java.lang.Object ref = pid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }
      void setPid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.Login)
    }
    
    static {
      defaultInstance = new Login(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.Login)
  }
  
  public interface ResLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string pid = 1;
    boolean hasPid();
    String getPid();
  }
  public static final class ResLogin extends
      com.google.protobuf.GeneratedMessage
      implements ResLoginOrBuilder {
    // Use ResLogin.newBuilder() to construct.
    private ResLogin(Builder builder) {
      super(builder);
    }
    private ResLogin(boolean noInit) {}
    
    private static final ResLogin defaultInstance;
    public static ResLogin getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResLogin getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_ResLogin_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_ResLogin_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private java.lang.Object pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPid() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      pid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.myking520.github.protocolbuf.NetTankManager.ResLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.myking520.github.protocolbuf.NetTankManager.ResLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.myking520.github.protocolbuf.NetTankManager.ResLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_ResLogin_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.myking520.github.protocolbuf.NetTankManager.internal_static_protocol_ResLogin_fieldAccessorTable;
      }
      
      // Construct using com.ele.net.server.proto.NetTankManager.ResLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.myking520.github.protocolbuf.NetTankManager.ResLogin.getDescriptor();
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.ResLogin getDefaultInstanceForType() {
        return com.myking520.github.protocolbuf.NetTankManager.ResLogin.getDefaultInstance();
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.ResLogin build() {
        com.myking520.github.protocolbuf.NetTankManager.ResLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.myking520.github.protocolbuf.NetTankManager.ResLogin buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.myking520.github.protocolbuf.NetTankManager.ResLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.myking520.github.protocolbuf.NetTankManager.ResLogin buildPartial() {
        com.myking520.github.protocolbuf.NetTankManager.ResLogin result = new com.myking520.github.protocolbuf.NetTankManager.ResLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.myking520.github.protocolbuf.NetTankManager.ResLogin) {
          return mergeFrom((com.myking520.github.protocolbuf.NetTankManager.ResLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.myking520.github.protocolbuf.NetTankManager.ResLogin other) {
        if (other == com.myking520.github.protocolbuf.NetTankManager.ResLogin.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string pid = 1;
      private java.lang.Object pid_ = "";
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPid() {
        java.lang.Object ref = pid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }
      void setPid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.ResLogin)
    }
    
    static {
      defaultInstance = new ResLogin(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.ResLogin)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ResLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ResLogin_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022tank_manager.proto\022\010protocol\"\024\n\005Login\022" +
      "\013\n\003pid\030\001 \002(\t\"\027\n\010ResLogin\022\013\n\003pid\030\001 \002(\tB*\n" +
      "\030com.ele.net.server.protoB\016NetTankManage" +
      "r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_Login_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_Login_descriptor,
              new java.lang.String[] { "Pid", },
              com.myking520.github.protocolbuf.NetTankManager.Login.class,
              com.myking520.github.protocolbuf.NetTankManager.Login.Builder.class);
          internal_static_protocol_ResLogin_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_ResLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ResLogin_descriptor,
              new java.lang.String[] { "Pid", },
              com.myking520.github.protocolbuf.NetTankManager.ResLogin.class,
              com.myking520.github.protocolbuf.NetTankManager.ResLogin.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
